const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const ui=Object.fromEntries(['score','health','power','round','status','healthBar','specialBar','powerDescription','toast','announcement'].map(id=>[id,document.getElementById(id)])),overlay=document.getElementById('overlay');
let last=0,raf,active=false,over=false,score=0,round=1,wave=1,spawnClock=1,toastClock=0,clearedBooks=0,waveSpawned=0,waveDefeated=0,bossSpawned=false;
const keys={left:false,right:false};
const waves=[
 {normal:5,delay:3.3,speed:58,hp:56},
 {normal:7,delay:1.55,speed:112,hp:72},
 {normal:8,delay:.8,speed:158,hp:88}
];
const books=[
 {name:'CHEMISTRY',sub:'Organic Chemistry',color:'#59d4bf',power:'CORROSIVE POTION',desc:'K throws a potion that damages nearby books over time.',type:'potion'},
 {name:'BIOLOGY',sub:'Cellular Biology',color:'#81c858',power:'FULL REGENERATION',desc:'Immediately restores all vitality.',type:'regen'},
 {name:'PHYSICS',sub:'Classical Mechanics',color:'#f0ba45',power:'SKATEBOARD ARMOR',desc:'Four seconds of fast movement and armored hits.',type:'physics'},
 {name:'HISTORY',sub:'American History',color:'#d3794d',power:'ERA ARSENAL',desc:'A random era weapon is selected when collected.',type:'history'}];
const historyWeapons=[
 {name:'SWORD',desc:'K slashes the closest textbook for heavy damage.',damage:85,range:160,color:'#e4e8ef'},
 {name:'MUSKET',desc:'K fires a long-range shot through the first textbook.',damage:110,range:420,color:'#c59b69'},
 {name:'RPG',desc:'K launches an explosive into the incoming crowd.',damage:135,range:400,color:'#f18647',blast:true},
 {name:'LASER GUN',desc:'K fires a beam through every textbook on the street.',damage:76,range:900,color:'#f45cbd',beam:true}
];
const player={x:210,hp:100,attack:0,cd:0,hurt:0,special:0,power:null,powerTime:0,powerCd:0,shield:0,rush:0,armor:0,jetpack:0,critical:false};let enemies=[],drops=[],sparks=[],potions=[],shots=[];
function reset(){score=0;wave=1;spawnClock=1;clearedBooks=0;waveSpawned=0;waveDefeated=0;bossSpawned=false;enemies=[];drops=[];sparks=[];potions=[];shots=[];Object.assign(player,{x:210,hp:100,attack:0,cd:0,hurt:0,special:0,power:null,powerTime:0,powerCd:0,shield:0,rush:0,armor:0,jetpack:0,critical:false});over=false;sync()}
function sync(){let loadout=player.power?.type==='jetpack';ui.score.textContent=String(clearedBooks);ui.health.textContent=Math.max(0,Math.ceil(player.hp));ui.healthBar.style.width=`${player.hp}%`;ui.round.textContent=String(wave).padStart(2,'0');ui.power.textContent=player.power?.power||'NO POWER';ui.powerDescription.textContent=loadout?'TAP C TO IGNITE THE JETPACK AND FIRE THE LASER GUN.':player.power?`TAP K TO USE • ${player.powerTime.toFixed(1)}s LEFT`:'Defeat a textbook and claim its study aid.';ui.specialBar.style.width=loadout?'100%':`${player.powerTime/3*100}%`}
function say(html){ui.toast.innerHTML=html;ui.toast.classList.add('show');toastClock=2.4}
let announcementTimer;function announce(title,detail){clearTimeout(announcementTimer);ui.announcement.innerHTML=`${title}<span>${detail}</span>`;ui.announcement.style.opacity=1;ui.announcement.style.transform='scale(1)';announcementTimer=setTimeout(()=>{ui.announcement.style.opacity=0;ui.announcement.style.transform='scale(.92)'},2600)}
function spawn(){let config=waves[wave-1];if(waveSpawned<config.normal){let book=books[Math.floor(Math.random()*books.length)];enemies.push({x:1140,hp:config.hp,max:config.hp,book,speed:config.speed,hit:0,cd:1.4+Math.random()});waveSpawned++;return}if(wave===3&&!bossSpawned&&enemies.length===0){let book={name:'ENTREPRENUERIAL',sub:'Finance',color:'#9d59e5',power:'FINAL EXAM',desc:'The final course stands in your way.',type:'boss'};let hp=config.hp*4.5;player.power={power:'JETPACK + LASER GUN',type:'jetpack',color:'#f45cbd'};player.powerTime=Infinity;player.powerCd=0;enemies.push({x:1140,hp,max:hp,book,speed:config.speed*.8,hit:0,cd:1.1,scale:1.58,boss:true});bossSpawned=true;say('<b>FINAL BOSS</b> Jetpack acquired — press C to fire.')}
}
function spark(x,y,color,n=9){for(let i=0;i<n;i++)sparks.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.7)*250,life:.45+Math.random()*.35,color})}
function defeat(e){let i=enemies.indexOf(e);if(i<0)return;enemies.splice(i,1);clearedBooks++;score+=e.boss?750:125;spark(e.x,440,e.book.color,20);if(e.boss){victory();return}drops.push({x:e.x,y:450,book:e.book,life:7,bob:0});waveDefeated++;if(waveDefeated===waves[wave-1].normal){let completed=wave;if(wave<3){wave++;waveSpawned=0;waveDefeated=0;spawnClock=1.4;if(wave===3){player.rush=0;player.armor=0;player.critical=false;say('<b>WAVE 3</b> Final coursework incoming.');announce(`ROUND ${completed} COMPLETED`,'FINAL COURSEWORK INCOMING')}else{say(`<b>WAVE ${wave}</b> Incoming textbooks are faster.`);announce(`ROUND ${completed} COMPLETED`,`ROUND ${wave} INCOMING`)}}else{spawnClock=.8;say('<b>FINAL BOSS APPROACHING</b> Prepare for Entreprenuerial Finance.');announce('ROUND 3 COMPLETED','BOSS BATTLE — ENTREPRENUERIAL FINANCE')}}else say(`<b>${e.book.name} DEFEATED</b> ${e.book.power} dropped.`)}
function attack(){if(!active||over||player.cd>0)return;player.attack=.18;player.cd=player.rush?.22:.42;let e=enemies.find(x=>Math.abs(x.x-player.x)<145);if(!e){spark(player.x+68,458,'#f6f3ec',5);return}let critical=player.critical,d=critical?72:26;e.hp=Math.max(0,e.hp-d);e.hit=.14;player.critical=false;player.special=Math.min(100,player.special+18);spark(e.x,450,critical?'#fff':'#f4bb41',12);if(e.hp===0)defeat(e)}
function damageEnemy(e,amount,color){e.hp=Math.max(0,e.hp-amount);e.hit=.18;spark(e.x,450,color,14);if(e.hp===0)defeat(e)}
function special(){if(!active||!player.power||player.powerTime<=0||player.powerCd>0)return;player.powerCd=.24;let power=player.power;if(power.type==='potion'){potions.push({x:player.x+28,y:423,vx:480,vy:-230,life:1.05});say('<b>CORROSIVE POTION</b> thrown.');return}if(power.type==='regen'){player.hp=100;spark(player.x,430,'#81c858',20);say('<b>FULL REGENERATION</b> restored vitality.');return}if(power.type==='physics'){player.rush=4;player.armor=4;spark(player.x,470,'#f0ba45',16);say('<b>SKATEBOARD ARMOR</b> activated for 4 seconds.');return}if(power.type==='history'){let weapon=power.weapon;if(weapon.name==='SWORD')shots.push({kind:'slash',x:player.x+48,y:439,life:.24,color:weapon.color});else if(weapon.name==='MUSKET')shots.push({kind:'bullet',x:player.x+58,y:438,vx:900,life:.55,color:weapon.color});else if(weapon.name==='RPG')shots.push({kind:'rocket',x:player.x+55,y:440,vx:510,life:.65,color:weapon.color});else shots.push({kind:'laser',x:player.x+55,y:438,life:.13,color:weapon.color});if(weapon.beam){enemies.slice().forEach(e=>damageEnemy(e,weapon.damage,weapon.color))}else if(weapon.blast){enemies.slice().forEach(e=>{if(e.x-player.x<weapon.range)damageEnemy(e,weapon.damage,weapon.color)})}else{let e=enemies.find(e=>e.x-player.x<weapon.range);if(e)damageEnemy(e,weapon.damage,weapon.color)}say(`<b>${weapon.name}</b> deployed.`);return}player.critical=true;say('<b>FOCUS MODE</b> next strike is critical.')}
function collect(d){let power={...d.book};if(power.type==='history'){let weapon=historyWeapons[Math.floor(Math.random()*historyWeapons.length)];power={...power,power:weapon.name,desc:weapon.desc,weapon}}player.power=power;player.powerTime=3;player.powerCd=0;spark(d.x,d.y,power.color,16);say(`<b>${power.power}</b> acquired. Tap K before it expires.`)}
function end(){over=true;active=false;ui.status.textContent='OUT OF SESSION';overlay.innerHTML=`<div class="overlay-kicker">FINAL SCORE ${Math.floor(score)}</div><h1>Study<br><em>Break</em></h1><p>The syllabus got the better of you this time.</p><button id="startButton">Fight Again</button>`;overlay.classList.add('visible');document.getElementById('startButton').onclick=start}
function update(dt){if(!active||over)return;round+=dt*.055;score+=dt*6;toastClock-=dt;if(toastClock<=0)ui.toast.classList.remove('show');let speed=player.rush?430:330;if(keys.left)player.x-=speed*dt;if(keys.right)player.x+=speed*dt;player.x=Math.max(90,Math.min(780,player.x));player.attack=Math.max(0,player.attack-dt);player.cd=Math.max(0,player.cd-dt);player.hurt=Math.max(0,player.hurt-dt);player.powerCd=Math.max(0,player.powerCd-dt);player.rush=Math.max(0,player.rush-dt);player.armor=Math.max(0,player.armor-dt);if(player.power){player.powerTime-=dt;if(player.powerTime<=0){say('<b>POWER EXPIRED</b> defeat another textbook.');player.power=null;player.powerTime=0}}spawnClock-=dt;if(spawnClock<=0){spawn();spawnClock=Math.max(.85,2.25-round*.08)+Math.random()*.6}enemies.forEach(e=>{e.cd-=dt;e.hit=Math.max(0,e.hit-dt);if(e.poison){e.poison-=dt;e.poisonTick=(e.poisonTick||0)+dt;if(e.poisonTick>=.5){e.poisonTick=0;damageEnemy(e,8,'#59d4bf')}if(e.hp<=0)return}if(e.x-player.x>88)e.x-=e.speed*dt;else if(e.cd<=0){e.cd=1.22;if(player.armor>0){spark(player.x,450,'#f0ba45',7);say('<b>SKATEBOARD ARMOR</b> absorbed the hit.')}else{player.hp-=8+round*1.2;player.hurt=.2;spark(player.x,450,'#ef294c',10);if(player.hp<=0)end()}}});for(let i=shots.length-1;i>=0;i--){let s=shots[i];s.life-=dt;if(s.vx)s.x+=s.vx*dt;if(s.life<=0)shots.splice(i,1)}for(let i=potions.length-1;i>=0;i--){let p=potions[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=520*dt;p.life-=dt;if(p.life<=0||p.y>=476){enemies.forEach(e=>{if(Math.abs(e.x-p.x)<130){e.poison=5;e.poisonTick=0;spark(e.x,430,'#59d4bf',16)}});spark(p.x,476,'#59d4bf',20);potions.splice(i,1)}}for(let i=drops.length-1;i>=0;i--){let d=drops[i];d.life-=dt;d.bob+=dt*5;if(Math.abs(d.x-player.x)<50){collect(d);drops.splice(i,1)}else if(d.life<0)drops.splice(i,1)}for(let i=sparks.length-1;i>=0;i--){let p=sparks[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt;p.life-=dt;if(p.life<=0)sparks.splice(i,1)}sync()}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}function text(t,x,y,size,color,align='left'){ctx.fillStyle=color;ctx.font=`${size}px Impact,Arial Narrow,Arial`;ctx.textAlign=align;ctx.fillText(t,x,y)}
function background(){ctx.clearRect(0,0,1080,640);let g=ctx.createLinearGradient(0,0,0,640);g.addColorStop(0,'#404d62');g.addColorStop(.58,'#1d2734');g.addColorStop(.59,'#4e5154');g.addColorStop(1,'#27282d');ctx.fillStyle=g;ctx.fillRect(0,0,1080,640);[0,90,205,300,430,545,670,810,925].forEach((x,i)=>{let h=100+(i%4)*30;rect(x,330-h,76,h,'#18212c');for(let y=350-h;y<325;y+=22)for(let a=9;a<68;a+=19)rect(x+a,y,7,9,'#f0ba45')});rect(0,330,1080,14,'#121820');rect(0,344,1080,296,'#47484c');for(let x=-100;x<1100;x+=190){ctx.strokeStyle='#d3b856';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x,640);ctx.lineTo(x+145,344);ctx.stroke()}rect(0,515,1080,5,'#24252a');text('CAMPUS DISTRICT',33,83,22,'rgba(255,255,255,.35)');text('STUDENT UNION  //  11:47 PM',33,109,12,'rgba(255,255,255,.46)')}
function person(){let x=player.x;ctx.save();ctx.translate(x,490);if(player.hurt>0)ctx.globalAlpha=.55;ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,45,42,9,0,0,7);ctx.fill();if(player.rush){ctx.fillStyle='#f0ba45';ctx.fillRect(-42,55,84,5);ctx.fillStyle='#1a1d23';ctx.beginPath();ctx.arc(-25,63,8,0,7);ctx.arc(25,63,8,0,7);ctx.fill()}ctx.fillStyle='#623a27';ctx.beginPath();ctx.arc(0,-74,18,0,7);ctx.fill();ctx.fillStyle='#151923';ctx.fillRect(-16,-91,32,10);ctx.fillStyle='#bb142e';ctx.beginPath();ctx.moveTo(-28,-52);ctx.lineTo(28,-52);ctx.lineTo(22,15);ctx.lineTo(-22,15);ctx.closePath();ctx.fill();text('O',0,-13,24,'#fff','center');ctx.fillStyle='#18202c';ctx.fillRect(-18,15,14,43);ctx.fillRect(4,15,14,43);ctx.fillStyle='#f6f3ec';ctx.fillRect(-23,57,23,6);ctx.fillRect(2,57,23,6);ctx.strokeStyle='#623a27';ctx.lineWidth=11;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-25,-40);ctx.lineTo(player.attack>0?65:-40,-4);ctx.stroke();ctx.beginPath();ctx.moveTo(25,-40);ctx.lineTo(player.attack>0?74:-1,5);ctx.stroke();if(player.armor){ctx.strokeStyle='#f0ba45';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-15,67,0,7);ctx.stroke()}ctx.restore()}
function book(e){ctx.save();ctx.translate(e.x,490);ctx.fillStyle='rgba(0,0,0,.38)';ctx.beginPath();ctx.ellipse(0,45,38,8,0,0,7);ctx.fill();ctx.fillStyle=e.hit?'#fff':e.book.color;ctx.fillRect(-31,-64,62,104);ctx.fillStyle='#151923';ctx.fillRect(-26,-58,52,6);text(e.book.name,0,-21,15,'#fff','center');ctx.font='10px Arial';ctx.fillStyle='#17191f';ctx.textAlign='center';ctx.fillText(e.book.sub,0,-5);ctx.fillStyle='#191b20';ctx.fillRect(-24,12,48,4);ctx.fillStyle='#f6f3ec';ctx.fillRect(-18,40,13,8);ctx.fillRect(5,40,13,8);ctx.fillStyle='#24252a';ctx.fillRect(-31,-79,62,7);ctx.fillStyle='#ef294c';let healthRatio=Math.max(0,Math.min(1,e.hp/e.max));ctx.fillRect(-29,-79,healthRatio*58,7);ctx.restore()}
function drop(d){ctx.save();ctx.translate(d.x,d.y-55+Math.sin(d.bob)*6);ctx.fillStyle=d.book.color;ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(17,0);ctx.lineTo(0,18);ctx.lineTo(-17,0);ctx.closePath();ctx.fill();text('K',0,6,17,'#17191f','center');ctx.restore()}
function potion(p){ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#dffef5';ctx.fillRect(-5,-12,10,5);ctx.fillStyle='#59d4bf';ctx.beginPath();ctx.arc(0,0,11,0,7);ctx.fill();ctx.restore()}
function equipped(){let p=player.power;if(!p)return;let x=player.x+55,y=441;ctx.save();ctx.translate(x,y);ctx.globalAlpha=.82+Math.sin(performance.now()/90)*.18;ctx.strokeStyle=p.color;ctx.fillStyle=p.color;ctx.lineWidth=5;if(p.type==='history'){let w=p.weapon;if(w.name==='SWORD'){ctx.strokeStyle=w.color;ctx.beginPath();ctx.moveTo(-4,12);ctx.lineTo(34,-25);ctx.stroke();ctx.strokeStyle='#6d4c35';ctx.beginPath();ctx.moveTo(-12,20);ctx.lineTo(5,3);ctx.stroke()}else if(w.name==='MUSKET'){ctx.fillStyle=w.color;ctx.fillRect(-15,-3,55,8);ctx.fillStyle='#333';ctx.fillRect(31,-6,22,4)}else if(w.name==='RPG'){ctx.fillStyle='#507847';ctx.fillRect(-10,-7,55,14);ctx.fillStyle='#f18647';ctx.beginPath();ctx.moveTo(45,-8);ctx.lineTo(61,0);ctx.lineTo(45,8);ctx.closePath();ctx.fill()}else{ctx.strokeStyle=w.color;ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-10,0);ctx.lineTo(53,0);ctx.stroke()}}else if(p.type==='potion'){ctx.fillStyle='#59d4bf';ctx.beginPath();ctx.arc(8,0,14,0,7);ctx.fill();ctx.fillStyle='#dffef5';ctx.fillRect(3,-20,10,8)}else if(p.type==='regen'){ctx.fillStyle='#81c858';ctx.fillRect(-6,-18,12,36);ctx.fillRect(-18,-6,36,12)}ctx.restore();text(`K  ${p.power}`,player.x+55,382,12,p.color,'center')}
function shot(s){ctx.save();ctx.globalAlpha=Math.max(0,s.life*3);if(s.kind==='bullet'){ctx.fillStyle=s.color;ctx.fillRect(s.x,s.y-2,20,4)}else if(s.kind==='rocket'){ctx.fillStyle='#507847';ctx.fillRect(s.x,s.y-5,26,10);ctx.fillStyle=s.color;ctx.beginPath();ctx.moveTo(s.x+26,s.y-7);ctx.lineTo(s.x+39,s.y);ctx.lineTo(s.x+26,s.y+7);ctx.closePath();ctx.fill()}else if(s.kind==='laser'){ctx.strokeStyle=s.color;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(1060,s.y);ctx.stroke()}else{ctx.strokeStyle=s.color;ctx.lineWidth=7;ctx.beginPath();ctx.arc(s.x,s.y,46,-1.3,1.3);ctx.stroke()}ctx.restore()}
function render(){background();drops.forEach(drop);potions.forEach(potion);enemies.forEach(book);person();equipped();shots.forEach(shot);sparks.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)});ctx.globalAlpha=1;text(`WAVE ${String(Math.ceil(round)).padStart(2,'0')}`,30,145,31,'#f6f3ec');text(wave===3?'FINAL EXAMINATION':'TEXTBOOKS INCOMING',30,166,13,'#f4bb41')}
function loop(t){let dt=Math.min(.032,(t-last)/1000||0);last=t;update(dt);render();raf=requestAnimationFrame(loop)}function start(){reset();active=true;overlay.classList.remove('visible');ui.status.textContent='FIGHTING';last=0;if(!raf)raf=requestAnimationFrame(loop)}window.startGame=start;
document.getElementById('startButton').onclick=start;window.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(['arrowleft','arrowright',' ','k','c'].includes(k)||e.code==='Space')e.preventDefault();if(k==='a'||k==='arrowleft')keys.left=true;if(k==='d'||k==='arrowright')keys.right=true;if(e.code==='Space'){if(!active)start();else attack()}if(k==='k'&&player.power?.type!=='jetpack')special();if(k==='c'&&active&&player.power?.type==='jetpack')jetpackSpecial()});window.addEventListener('keyup',e=>{let k=e.key.toLowerCase();if(k==='a'||k==='arrowleft')keys.left=false;if(k==='d'||k==='arrowright')keys.right=false});render();
function victory(){over=true;active=false;ui.status.textContent='DEAN\'S LIST';overlay.innerHTML=`<div class="overlay-kicker">FINAL SCORE ${Math.floor(score)}</div><h1>Class<br><em>Dismissed</em></h1><p>Entreprenuerial Finance has been cleared. The quad is yours.</p><button id="startButton">Play Again</button>`;overlay.classList.add('visible');document.getElementById('startButton').onclick=start}
function jetpackSpecial(){if(!active||player.powerCd>0)return;player.powerCd=.24;player.jetpack=3.5;player.rush=3.5;player.armor=3.5;shots.push({kind:'laser',x:player.x+55,y:410,life:.13,color:'#f45cbd'});enemies.slice().forEach(e=>damageEnemy(e,76,'#f45cbd'));spark(player.x,430,'#f45cbd',20);say('<b>JETPACK IGNITED</b> Laser gun fired.')}
const baseSpecial=special,baseCollect=collect,baseBook=book,basePerson=person;
special=function(){if(player.power?.type==='jetpack')return jetpackSpecial();return baseSpecial()};
collect=function(d){if(wave===3&&player.power?.type==='jetpack'){spark(d.x,d.y,'#f45cbd',8);return}baseCollect(d)};
book=function(e){if(!e.scale)return baseBook(e);ctx.save();ctx.translate(e.x,490);ctx.scale(e.scale,e.scale);ctx.translate(-e.x,-490);baseBook(e);ctx.restore()};
person=function(){let hover=player.jetpack?42+Math.sin(performance.now()/90)*6:0;ctx.save();ctx.translate(0,-hover);basePerson();ctx.restore();if(player.power?.type!=='jetpack')return;let x=player.x;ctx.save();ctx.translate(x,430-hover);ctx.fillStyle='#303747';ctx.fillRect(-42,-8,14,37);ctx.fillRect(28,-8,14,37);ctx.fillStyle='#f45cbd';ctx.fillRect(-39,29,8,player.jetpack?30:7);ctx.fillRect(31,29,8,player.jetpack?30:7);ctx.strokeStyle='#f45cbd';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(26,4);ctx.lineTo(72,4);ctx.stroke();ctx.restore()};
update=function(dt){if(!active||over)return;round=wave;score+=dt*6;toastClock-=dt;if(toastClock<=0)ui.toast.classList.remove('show');let speed=player.rush?430:330;if(keys.left)player.x-=speed*dt;if(keys.right)player.x+=speed*dt;player.x=Math.max(90,Math.min(780,player.x));player.attack=Math.max(0,player.attack-dt);player.cd=Math.max(0,player.cd-dt);player.hurt=Math.max(0,player.hurt-dt);player.powerCd=Math.max(0,player.powerCd-dt);player.rush=Math.max(0,player.rush-dt);player.armor=Math.max(0,player.armor-dt);player.jetpack=Math.max(0,player.jetpack-dt);if(player.power&&player.power.type!=='jetpack'){player.powerTime-=dt;if(player.powerTime<=0){say('<b>POWER EXPIRED</b> defeat another textbook.');player.power=null;player.powerTime=0}}let config=waves[wave-1];spawnClock-=dt;if(spawnClock<=0){spawn();spawnClock=wave===3&&waveSpawned===config.normal&&!bossSpawned?.75:config.delay}enemies.forEach(e=>{e.cd-=dt;e.hit=Math.max(0,e.hit-dt);if(e.poison){e.poison-=dt;e.poisonTick=(e.poisonTick||0)+dt;if(e.poisonTick>=.5){e.poisonTick=0;damageEnemy(e,8,'#59d4bf')}if(e.hp<=0)return}if(e.x-player.x>(e.boss?112:88))e.x-=e.speed*dt;else if(e.cd<=0){e.cd=e.boss?.8:1.22;if(player.armor>0){spark(player.x,450,'#f0ba45',7);say('<b>ARMOR</b> absorbed the hit.')}else{player.hp-=e.boss?22:8+wave*1.2;player.hurt=.2;spark(player.x,450,'#ef294c',10);if(player.hp<=0)end()}}});for(let i=shots.length-1;i>=0;i--){let s=shots[i];s.life-=dt;if(s.vx)s.x+=s.vx*dt;if(s.life<=0)shots.splice(i,1)}for(let i=potions.length-1;i>=0;i--){let p=potions[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=520*dt;p.life-=dt;if(p.life<=0||p.y>=476){enemies.forEach(e=>{if(Math.abs(e.x-p.x)<130){e.poison=5;e.poisonTick=0;spark(e.x,430,'#59d4bf',16)}});spark(p.x,476,'#59d4bf',20);potions.splice(i,1)}}for(let i=drops.length-1;i>=0;i--){let d=drops[i];d.life-=dt;d.bob+=dt*5;if(Math.abs(d.x-player.x)<50){collect(d);drops.splice(i,1)}else if(d.life<0)drops.splice(i,1)}for(let i=sparks.length-1;i>=0;i--){let p=sparks[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt;p.life-=dt;if(p.life<=0)sparks.splice(i,1)}sync()};
const baseReset=reset,baseDefeat=defeat,baseSync=sync;defeat=function(e){let isBoss=e.boss;baseDefeat(e);if(isBoss)clearedBooks--};sync=function(){baseSync();ui.score.textContent=String(clearedBooks)};reset=function(){baseReset();clearTimeout(announcementTimer);ui.announcement.style.opacity=0;ui.announcement.style.transform='scale(.92)'};
